export const environment = {
  production: true,
  apiBaseUrl: '/api',
  calmingResourcesEndpoint: '/calmingResources',
  favoriteResourcesEndpoint: '/favoriteResources',
  communicationRequestsEndpoint: '/communicationRequests',
  calmSessionsEndpoint: '/calmSessions',
  profilesEndpoint: '/profiles',
  caregiversEndpoint: '/caregivers',
  actionGuidesEndpoint: '/actionGuides',
  sosSessionsEndpoint: '/sosSessions',
  accountsEndpoint: '/accounts',
  institutionsEndpoint: '/institutions',
  myPlanEndpoint: '/subscriptions',
  paymentsEndpoint: '/payments',
  ticketsEndpoint: '/tickets',
};
